### ISSUE TITLE
oidc-spa  React now working

### ISSUE THREAD

**Issue by edgars** [p2-inc/examples#13]
Hi there,

Is there a required .env config or extra config to make the example to run correctly?

This is the error that I am getting:

<img width="1204" alt="image" src="https://github.com/user-attachments/assets/e87abdfe-8e04-45b4-9720-4cce34c3bc02">

**Comment by pnzrr** [comment]
you need to most likely update the configuration being used with the correct keycloak system

**Comment by pnzrr** [comment]
Unable to repro

**Comment by edgars** [comment]
Well, where should be located such config file or .env file?

**Comment by pnzrr** [comment]
For the oidc-spa example,

https://github.com/p2-inc/examples/blob/main/frameworks/reactjs/oidc-spa/src/index.tsx#L8

```
export const { OidcProvider, useOidc, getOidc } = createReactOidc({
  // NOTE: If you don't have the params right away see note below.
  issuerUri: "https://app.phasetwo.io/auth/realms/p2examples",
  clientId: "reactjs-example",
  /**
   * Vite:  `publicUrl: import.meta.env.BASE_URL`
   * CRA:   `publicUrl: process.env.PUBLIC_URL`
   * Other: `publicUrl: "/"` (Usually)
   */
  publicUrl: process.env.BASE_URL,
});
```
